signatory: /integration-tests/signatory/cmd/signatory/main.go
signatory_wdir: /integration-tests/signatory
tezos_client_dir: /integration-tests/signatory/integration/client_data
signatory_config: /integration-tests/signatory/signatory.yaml
test_cases:
  # File 
  - account: test123
    address: tz3hRZUScFCcEVhdDjXWoyekbgd1Gatga6mp
    http_code: 200
    expect_signature_valid: true
    public_key: p2pk67qRiKaQAxLBRfmnfvQHTTsZQEJrHhEteM3pZr1suJ8SXAt42sU
  - account: "test10"
    address: "tz2UBGrEBKzzW6hjXjxxiQFJNg6WR2bm6GEN"
    http_code: 200
    expect_signature_valid: true
    public_key: "sppk7b66BhTvYZm5iPds9at3bzhEMt94qF32WJKFcFkQHy2PkDENBTj"
  - account: "test1"
    address: "tz1b9kV41KV9N3sp69ycLdSoZ2Ak8jXwtNPv"
    http_code: 200
    expect_signature_valid: true
    public_key: "edpkuhmrbunxumoiVdQuxBZUPMmwkPt7yLtY5Qnua3VJVTLWr3vXXa"
  # Azure
  # - account: "testhsm1"
  #   address: "tz29DwfjrzrMXoktq2V74aV5HV997AczJhvU"
  #   http_code: 200
  #   expect_signature_valid: true
  #   public_key: "sppk7bhADQLEc6umGxm817seoomyYNsCquV7Fqxh1Qvttu4HjiSfomD"
  # - account: "testhsm2"
  #   address: "tz3hRZUScFCcEVhdDjXWoyekbgd1Gatga6mp"
  #   http_code: 200
  #   expect_signature_valid: true
  #   public_key: "p2pk67qRiKaQAxLBRfmnfvQHTTsZQEJrHhEteM3pZr1suJ8SXAt42sU"
  # Invalid  
  - account: "test1"
    address: "tz1b9kV41KV9N3sp69ycLdSoZ2Ak8jXwtNPw"
    http_code: 403
    expect_signature_valid: false
    public_key: ""